# Generated by Django 6.0.6 on 2026-06-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=250, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=250, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=250, null=True, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name='Maqola matni')),
                ('content_uz', models.TextField(null=True, verbose_name='Maqola matni')),
                ('content_en', models.TextField(null=True, verbose_name='Maqola matni')),
                ('content_ru', models.TextField(null=True, verbose_name='Maqola matni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
            },
        ),
    ]
